### ISSUE TITLE
Validation error on valid vat

### ISSUE THREAD

**Issue by ericuss** [zapadi/vies-dotnet#16]
Hi

I'm not sure if I made something wrong, but I have problems  validating a VAT number. I create a test project to test the library before use in my project.  The sample VAT is IE3041081MH (I try to split into country code and vat number and not solves anything)

My code:
`   
 [Fact]
  public async Task HappyPath()
  {
      var viesManager = new ViesManager();

      var resultIsValid = ViesManager.IsValid("IE3041081MH");
      Assert.True(resultIsValid.IsValid, "IE3041081MH" + " is invalid");
      var resultIsActive = await viesManager.IsActive("IE3041081MH");

      Assert.True(resultIsActive.IsValid, "IE3041081MH"  + " is inactive");
  }
`
When I try in the VIES web, the code is ok.

![image](https://user-images.githubusercontent.com/4225477/203099191-9658c4f1-1de1-422d-9489-857f78d59c73.png)

![image](https://user-images.githubusercontent.com/4225477/203099253-555b8866-47c5-455c-b692-d184b1567d59.png)

Thanks for your help and I don't know if I commit a mistake.

**Comment by daef** [comment]
works for me:
![image](https://github.com/zapadi/vies-dotnet/assets/2098598/f29657fe-5c10-47cb-9d59-076b4d5b33e2)
